Switched to GCC from Clang for macOS users due to a compiling bug.
Error: 'redefinition of typedef 'ParseBlock' is a C11 feature', 'redefinition of typedef 'ParseValue' is a C11 feature'